### ISSUE TITLE
update_server_embed can run on server ready

### ISSUE THREAD

**Issue by mollybeam** [Digital-Controllers/discord-bot#20]
per title. The example given in the discord.py docs is this:

```py
from discord.ext import tasks, commands

class MyCog(commands.Cog):
    def __init__(self, bot):
        self.index = 0
        self.bot = bot
        self.printer.start()

    def cog_unload(self):
        self.printer.cancel()

    @tasks.loop(seconds=5.0)
    async def printer(self):
        print(self.index)
        self.index += 1

    @printer.before_loop
    async def before_printer(self):
        print('waiting...')
        await self.bot.wait_until_ready()
```

This could easily be applied to update_server_embed, and I'll work on it if that's wanted. This would remove the requirement to run the /update_embed command when the bot is updated.

If this is something that is wanted, then I can work on it, but I'm not sure if there are reasons why we're _not_ doing this yet.

**Comment by notmisery** [comment]
I'd say if you can implement something that turns a manual process into an automatic process it's (generally) probably worth it to do.  So I say go for it

**Comment by QuantifyGG** [comment]
This may be well integrated into this issue: #25 
We'll need to rework our embed updates anyway and automatic restarting of previously-posted embeds will be part of that.

**Comment by notmisery** [comment]
Agreed.  I'll close this issue and make a comment in the other and tag beam.
