### ISSUE TITLE
Further Embed Customisation

### ISSUE THREAD

**Issue by QuantifyGG** [Digital-Controllers/discord-bot#25]
At the moment, our embed code is designed solely for use in the DC server. This works fine but it would be brilliant to make our bot publicly accessible.
This would probably involve a refactor of our current embed routines to ensure embeds update globally in a safe and efficient manner while storing their identifiers/guild identifiers in an SQL database and accounting for various edge cases such as a channel/embed being deleted, while also creating commands to allow external server administrators to create embeds in a simple manner.

This would also involve a rework of the bot's permissions and since we're using interactions to a great extent, we should be able to strip down the required perms significantly. The ultimate goal is to not require the reading of messages whatsoever, so an implementation should not have to search for messages in a channel and should rather immediately fetch and store the message id from the message object created.

I'm not quite sure where to start on this so please do give me your thoughts and ideas, and we'll see how to go about it.

**Comment by notmisery** [comment]
@mollybeam We're going to add your last issue posted to this one.  Just makes sense we're already gonna be doing a huge overhaul.

https://github.com/Digital-Controllers/discord-bot/issues/20#issue-1716675706

**Comment by QuantifyGG** [comment]
This has been implemented successfully. Keeping issue open as we will be working with this code heavily in the coming weeks.

**Comment by QuantifyGG** [comment]
Issue closed due to new PR #37
