### ISSUE TITLE
METAR to Plain English

### ISSUE THREAD

**Issue by mollybeam** [Digital-Controllers/discord-bot#9]
Not everyone has the knowledge to read METAR reports by eye, and while copy/pasting a METAR report into a website is not difficult, it would enhance the user experience if this functionality were available through the bot. 
I suggest a standalone `/read-metar` command, which will take a METAR report as an input and respond with the plain english representation of it, and a modification to the `/metar` command which includes the plain english representation after the METAR report.

**Comment by notmisery** [comment]
Waiting for code to be reviewed and merged from my fork.

Issue closed.
